### ISSUE TITLE
Что нужно добавить и исправить до первого релиза?

### ISSUE THREAD

**Issue by Faridik** [Faridik/Carolyn#8]
- [] Из-за кэширования \sub и \unsub работают не совсем так, как хотелось бы. Надо подумать, что и как стоит исправить. Возможно, сделать какое-то кд на команду? Есть ли такое вообще?
- [] Подумать о том, как реализовать рассылку с результатами КР. Или забить на такую рассылку и сказать, чтобы они сами смотрели через /grades?
- [] Очистка контекстных данных.

**Comment by mifarse** [comment]
Выполнили задачу, но есть баги. Баги будут в другом тикете.
